// Mocks generated by Mockito 5.4.5 from annotations
// in realview/test/features/authors/domain/use_case/get_authors_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:realview/features/authors/domain/entity/result_entity/get_authors_result.dart'
    as _i2;
import 'package:realview/features/authors/domain/repo/authors_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAuthorsResult_0 extends _i1.SmartFake implements _i2.GetAuthorsResult {
  _FakeGetAuthorsResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthorsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthorsRepo extends _i1.Mock implements _i3.AuthorsRepo {
  @override
  _i4.Future<_i2.GetAuthorsResult> getAuthors({required String? keyword}) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthors, [], {#keyword: keyword}),
            returnValue: _i4.Future<_i2.GetAuthorsResult>.value(
              _FakeGetAuthorsResult_0(
                this,
                Invocation.method(#getAuthors, [], {#keyword: keyword}),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.GetAuthorsResult>.value(
              _FakeGetAuthorsResult_0(
                this,
                Invocation.method(#getAuthors, [], {#keyword: keyword}),
              ),
            ),
          )
          as _i4.Future<_i2.GetAuthorsResult>);
}
