// Mocks generated by Mockito 5.4.5 from annotations
// in realview/test/features/author_detail/domain/use_case/get_author_detail_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:realview/features/author_detail/domain/entity/result_entity/get_author_detail_result.dart'
    as _i2;
import 'package:realview/features/author_detail/domain/repo/author_detail_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAuthorDetailResult_0 extends _i1.SmartFake implements _i2.GetAuthorDetailResult {
  _FakeGetAuthorDetailResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthorDetailRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthorDetailRepo extends _i1.Mock implements _i3.AuthorDetailRepo {
  @override
  _i4.Future<_i2.GetAuthorDetailResult> getAuthorDetail({required String? authorId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthorDetail, [], {#authorId: authorId}),
            returnValue: _i4.Future<_i2.GetAuthorDetailResult>.value(
              _FakeGetAuthorDetailResult_0(
                this,
                Invocation.method(#getAuthorDetail, [], {#authorId: authorId}),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.GetAuthorDetailResult>.value(
              _FakeGetAuthorDetailResult_0(
                this,
                Invocation.method(#getAuthorDetail, [], {#authorId: authorId}),
              ),
            ),
          )
          as _i4.Future<_i2.GetAuthorDetailResult>);
}
